### PR TITLE
Add API Reference page

### PR DESCRIPTION
**Pull request by Zanshe**
This replaces the old website with the foundation for the new API Reference page. The result can be viewed at https://zanshe.github.io/tiden/

@mikabytes Note that you will have to change the settings for the GitHub Page to be based on the `main` branch and `/docs` folder once this is merged. You can also delete the `gh-pages` branch.

### CODE REVIEW

**Comment by mikabytes** [comment]
This PR is from `main` branch to `main` branch. So `gh-pages` isn't even a thing here :)

**Comment by mikabytes** [comment]
Hmm, I wonder if we could have a navigation bar somewhere with two entries `About`` and `API`. Then API will be what's already here, and just copy the whole `README.md` into the About section?

That way we have some kind of description when someone visits the page. Even if its not completely done, it's still something.

**Comment by Zanshe** [comment]
> This PR is from `main` branch to `main` branch. So `gh-pages` isn't even a thing here :)

tidenjs has a branch called `gh-pages`, what I meant is that that branch will be made obsolete once the changes I mentioned have been made.

> Hmm, I wonder if we could have a navigation bar somewhere with two entries About and API.

Sure, I'll see what I can do

**Comment by Zanshe** [comment]
@mikabytes Well, there's a lot of copy-pasted code, but we have an About page ready to be reviewed now :)

**Comment by mikabytes** [comment]
Good stuff! Merging this :)

**Pull request merged**
